# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  install-tlacli:
    status:
      - which tlacli
    cmds:
      - python3 -m pip install tlacli
  test:
    desc: run all tests
    deps:
      - install-tlacli
    cmds:
      # - tlacli check simple-tla/struct.tla --invariant IsCorrect
      - tlacli check simple-tla/seq.tla --invariant IsCorrect
      - tlacli check simple-tla/set.tla --invariant IsCorrect
      - tlacli check simple-tla/bool.tla --invariant IsCorrect
      - tlacli check simple-tla/int.tla --invariant IsCorrect

  link:
    desc: create symlinks for simple-tla in examples/
    silent: true
    status:
      - test -e ./examples/init.tla
    cmds:
      - ln -s $PWD/simple-tla/bool.tla ./examples/
      - ln -s $PWD/simple-tla/init.tla ./examples/
      - ln -s $PWD/simple-tla/int.tla ./examples/
      - ln -s $PWD/simple-tla/seq.tla ./examples/
      - ln -s $PWD/simple-tla/set.tla ./examples/
      - ln -s $PWD/simple-tla/struct.tla ./examples/
      - ln -s $PWD/simple-tla/temp.tla ./examples/

  run:
    desc: run an example
    deps:
      - install-tlacli
      - link
    cmds:
      - tlacli check {{.CLI_ARGS}}
